# Generated by Django 3.2.9 on 2022-01-25 08:19

import apis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=200, unique=True)),
                ('Book_title', models.CharField(max_length=500)),
                ('Book_Author', models.CharField(max_length=500)),
                ('Year_of_Publication', models.CharField(max_length=300, null=True)),
                ('Publisher', models.CharField(max_length=300)),
                ('img_url_S', models.ImageField(blank=True, null=True, upload_to=apis.models.upload_path)),
                ('img_url_M', models.ImageField(blank=True, null=True, upload_to=apis.models.upload_path)),
                ('img_url_L', models.ImageField(blank=True, null=True, upload_to=apis.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('isbn', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='savesearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('booktitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=200)),
                ('Age', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('order_user_name', models.CharField(max_length=200)),
                ('order_address', models.TextField(max_length=500)),
                ('delevery_status', models.BooleanField(blank=True, null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apis.books')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='apis.books')),
            ],
        ),
    ]
