# Generated by Django 3.2.9 on 2021-12-12 09:59

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=200, unique=True)),
                ('Book_title', models.CharField(max_length=200)),
                ('Book_Author', models.CharField(max_length=200)),
                ('Year_of_Publication', models.IntegerField(null=True)),
                ('Publisher', models.CharField(max_length=200)),
                ('img_url_S', models.FileField(blank=True, null=True, upload_to=apis.models.upload_path)),
                ('img_url_M', models.FileField(blank=True, null=True, upload_to=apis.models.upload_path)),
                ('img_url_L', models.FileField(blank=True, null=True, upload_to=apis.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('isbn', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=200)),
                ('Age', models.IntegerField(null=True)),
            ],
        ),
    ]
