# Generated by Django 3.1.3 on 2021-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='Location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
