# Generated by Django 3.1.3 on 2021-12-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20211213_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='location',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_id',
        ),
    ]
