# Generated by Django 3.2.9 on 2022-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('isbn', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
