# Generated by Django 3.2.9 on 2022-01-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_rating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='savesearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('booktitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
