# Generated by Django 3.2.9 on 2022-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
