# Generated by Django 3.2.9 on 2022-01-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
