# Generated by Django 3.2.9 on 2022-01-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_alter_userdata_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('book', models.ManyToManyField(related_name='cartbooks', to='apis.Books')),
            ],
        ),
    ]
