# Generated by Django 3.2.9 on 2022-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ManyToManyField(to='apis.Books'),
        ),
    ]
