# Generated by Django 3.2.9 on 2022-01-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_cart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ManyToManyField(related_name='book', to='apis.Books'),
        ),
    ]
