# Generated by Django 3.2.9 on 2022-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_auto_20220117_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
