# Generated by Django 3.2.9 on 2022-01-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_orders_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orders',
        ),
        migrations.AddField(
            model_name='orders',
            name='orders',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apis.books'),
            preserve_default=False,
        ),
    ]
