# Generated by Django 3.2.9 on 2022-01-19 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20220118_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delevery_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_address',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='order_user_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
