# Generated by Django 3.2.9 on 2021-12-10 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
        ('rating', '0002_rating_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customUser.customuser'),
        ),
    ]
