# Generated by Django 3.2.9 on 2021-12-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
