# Generated by Django 3.2.9 on 2021-12-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
