# Generated by Django 3.2.9 on 2021-12-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
